name: Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ windows-latest ]
        platform: [ x64 ]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run tests
      shell: pwsh
      run: .\run_all.ps1
